/**
 * Flat list of all documentation pages for search.
 * Synced with Sidebar navItems.
 */
export const docsPages: { label: string; path: string }[] = [
  { label: 'Introduction', path: '/get-started' },
  { label: 'Foundations overview', path: '/foundations' },
  { label: 'Colors', path: '/foundations/colors' },
  { label: 'Icons', path: '/foundations/icons' },
  { label: 'Typography', path: '/foundations/typography' },
  { label: 'Spacing', path: '/foundations/spacing' },
  { label: 'Themes', path: '/foundations/themes' },
  { label: 'Elevation', path: '/foundations/elevation' },
  { label: 'Components overview', path: '/components' },
  { label: 'Accordion', path: '/components/accordion' },
  { label: 'Alert dialog', path: '/components/alert-dialog' },
  { label: 'Avatar', path: '/components/avatar' },
  { label: 'Badge', path: '/components/badge' },
  { label: 'Breadcrumbs', path: '/components/breadcrumbs' },
  { label: 'Button', path: '/components/button' },
  { label: 'Input', path: '/components/input' },
  { label: 'Calendar', path: '/components/calendar' },
  { label: 'Card', path: '/components/card' },
  { label: 'Chart', path: '/components/chart' },
  { label: 'Checkbox', path: '/components/checkbox' },
  { label: 'Date picker', path: '/components/date-picker' },
  { label: 'Data table', path: '/components/data-table' },
  { label: 'Dropdown', path: '/components/dropdown' },
  { label: 'Link', path: '/components/link' },
  { label: 'Menu bar', path: '/components/menubar' },
  { label: 'Pagination', path: '/components/pagination' },
  { label: 'Progress bar', path: '/components/progress-bar' },
  { label: 'Radio button', path: '/components/radio-button' },
  { label: 'Search', path: '/components/search' },
  { label: 'Select', path: '/components/select' },
  { label: 'Tabs', path: '/components/tabs' },
  { label: 'Toast', path: '/components/toast' },
  { label: 'Tooltips', path: '/components/tooltips' },
  { label: 'Patterns overview', path: '/patterns' },
  { label: 'Sidebar', path: '/patterns/sidebar' },
  { label: 'Command', path: '/patterns/command' },
  { label: 'Sheet', path: '/patterns/sheet' },
  { label: 'Examples', path: '/examples' },
  { label: 'Transaction list', path: '/examples?demo=transaction-list' },
];
